export { default as Header } from './Header'
export { default as Hero } from './Hero'
export { default as CTA } from './CTA'
export { default as Services } from './Services'
export { default as SomosCherza } from './SomosCherza'
export { default as Contacto } from './Contacto'
export { default as Footer } from './Footer'
